import { TokenSet } from "./tokens.js";

/**
 * Emit human-readable CSS + Tailwind config from an extracted TokenSet.
 *
 * The output is deliberately framework-neutral: both emitters produce plain
 * strings so the caller decides how to deliver them (write to disk, put in
 * a PR, paste into a style guide). Every color, typography, and spacing
 * token becomes a predictable identifier — tests pin the exact shape so we
 * don't drift into design-system bikeshedding on every edit.
 */

export interface StyleOutput {
  readonly css: string;
  readonly tailwind: string;
}

export function generateStyles(tokens: TokenSet): StyleOutput {
  return {
    css: generateCss(tokens),
    tailwind: generateTailwind(tokens),
  };
}

export function generateCss(tokens: TokenSet): string {
  const lines: string[] = [":root {"];
  tokens.colors.forEach((c, i) => {
    lines.push(`  --color-${i + 1}: ${c.hex};`);
  });
  tokens.spacing.forEach((s) => {
    lines.push(`  --space-${s.name}-${s.valuePx}: ${s.valuePx}px;`);
  });
  tokens.typography.forEach((t, i) => {
    const idx = i + 1;
    lines.push(`  --font-${idx}-family: "${t.fontFamily}";`);
    lines.push(`  --font-${idx}-weight: ${t.fontWeight};`);
    lines.push(`  --font-${idx}-size: ${t.fontSize}px;`);
    if (t.lineHeightPx !== null) {
      lines.push(`  --font-${idx}-line-height: ${t.lineHeightPx}px;`);
    }
  });
  lines.push("}");
  return lines.join("\n") + "\n";
}

export function generateTailwind(tokens: TokenSet): string {
  const colorEntries = tokens.colors
    .map((c, i) => `        "c${i + 1}": "${c.hex}",`)
    .join("\n");
  const spacingEntries = tokens.spacing
    .map((s) => `        "${s.name}-${s.valuePx}": "${s.valuePx}px",`)
    .join("\n");
  const fontFamilyEntries = Array.from(
    new Set(tokens.typography.map((t) => t.fontFamily)),
  )
    .map((f, i) => `        "family-${i + 1}": ["${f}"],`)
    .join("\n");
  const fontSizeEntries = tokens.typography
    .map(
      (t, i) =>
        `        "t${i + 1}": ["${t.fontSize}px"${
          t.lineHeightPx !== null ? `, { lineHeight: "${t.lineHeightPx}px" }` : ""
        }],`,
    )
    .join("\n");

  return [
    "// Generated by @vibeflow/design-bridge — do not hand-edit.",
    "module.exports = {",
    '  theme: {',
    '    extend: {',
    '      colors: {',
    colorEntries,
    '      },',
    '      spacing: {',
    spacingEntries,
    '      },',
    '      fontFamily: {',
    fontFamilyEntries,
    '      },',
    '      fontSize: {',
    fontSizeEntries,
    '      },',
    '    },',
    '  },',
    "};",
    "",
  ]
    .filter((l) => l !== "")
    .join("\n");
}
